const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const dungeon='1,0,0,1,3,7,16,7,5,18,9,3,20';
async function snapshot(p){return p.evaluate(()=>nativeSnapshot());}
async function checkpoint(p,changes={},growth='8,0,0,0,0,0,0,0,0,0',map=dungeon){await p.evaluate(({changes,growth,map})=>{const d=nativeSaveData();Object.assign(d.state,{location:2,x:51,y:47,px:2,py:7,hp:50,food:100,gold:100,experience:1,quest:3,clue:1,blessing:1,resolution:1,turn:0,time:0},changes);d.dungeon=map;d.growth=growth;nativeRestore(JSON.stringify(d));},{changes,growth,map});}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});try{
 for(const [monad,width,height]of [['ariel',1280,720],['samael',844,390],['raphael',390,844],['jophiel',1280,720],['lilith',390,844]]){
  const p=await b.newPage({viewport:{width,height},hasTouch:width<1000}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.waitForSelector('#welcome[open]');await p.click('#choose-direct');await p.click('[data-monad="'+monad+'"]');await p.click('#begin');await checkpoint(p);await p.click('#native-power');let s=await snapshot(p);assert.equal(s.light,5);assert.equal(s.turn,1);assert.equal(s.time,1);assert.equal(s.food,99.9);
  if(monad==='ariel'){assert.equal(s.hp,53);assert.equal(s.ward,2);}if(monad==='samael'){assert.equal(s.hp,50);assert.equal(s.experience,13);assert.equal((await p.evaluate(()=>nativeSaveData().dungeon)).split(',')[6],'0');}
  if(monad==='raphael'){assert.equal(s.hp,80);assert.equal(s.ward,0);}if(monad==='jophiel'){assert.equal(s.hp,50);assert.equal(s.focus,5);assert.equal((await p.evaluate(()=>nativeSaveData().growth)).split(',')[7],'2');}if(monad==='lilith'){assert.equal(s.hp,50);assert.equal(s.veil,2);assert.equal(s.focus,9);}
  await p.screenshot({path:'/tmp/quest-growth-'+monad+'.png'});const saved=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),saved);
  // Reject malformed, unowned gear and impossible effect payloads atomically.
  for(const growth of ['999,0,0,0,0,0,0,0,0,0','5,0,1,0,0,0,0,0,0,0','5,0,0,0,0,0,0,99,0,0','5,0,0,0,0,0,0,0,0,999999999999999999999999999999999999999999']){assert(await p.evaluate(growth=>{const d=nativeSaveData();d.growth=growth;try{nativeRestore(JSON.stringify(d));return false;}catch{return true;}},growth));assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),saved);}
  if(monad==='ariel'||monad==='jophiel'||monad==='lilith'){await p.evaluate(()=>{nativeAct(5);nativeAct(5);});s=await snapshot(p);assert.equal(s.ward,0);assert.equal(s.veil,0);const hp=s.hp;await p.evaluate(()=>nativeAct(5));assert.equal((await snapshot(p)).hp,hp-4);}
  if(monad==='lilith'){await checkpoint(p);await p.click('#native-power');await p.click('[data-native="8"]');s=await snapshot(p);assert.equal(s.focus,0);assert.equal(s.veil,0);assert.equal(s.experience,13);}
  // Failure to cast is free. Use C entry point to check disabled-button enforcement too.
  await checkpoint(p,{},'2,0,0,0,0,0,0,0,0,0');const low=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.evaluate(()=>nativeAct(12));assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),low);
  await checkpoint(p,{},'8,0,0,0,0,0,0,0,0,0','1,0,0,1,3,7,0,7,5,18,9,3,20');if(monad==='samael'||monad==='jophiel'){const noTarget=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.evaluate(()=>nativeAct(12));assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),noTarget);}
  await checkpoint(p,{location:0,x:47,y:35,px:0,py:0},'2,0,0,0,0,0,0,0,0,0');await p.evaluate(()=>nativeAct(5));assert.equal((await snapshot(p)).light,3);await p.evaluate(()=>nativeAct(6));assert.equal((await snapshot(p)).light,8);
  if(monad==='raphael'){await p.click('#native-power');s=await snapshot(p);assert.equal(s.hp,82);assert.equal(s.light,5);assert.equal(s.time,1);}
  else{const outside=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.evaluate(()=>nativeAct(12));assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),outside);}
  // Old native saves receive the correct level and full Light without altering the journey.
  await p.evaluate(()=>{const d=nativeSaveData();d.version=3;delete d.growth;d.state.experience=102;nativeRestore(JSON.stringify(d));});s=await snapshot(p);assert.equal(s.level,4);assert.equal(s.maxLight,14);assert.equal(s.light,14);assert.equal(s.owned,0);
  assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS native gift, costs, effects, atomic import and old-save levels',monad);await p.close();
 }
 const p=await b.newPage();await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.waitForSelector('#welcome[open]');await p.click('#choose-direct');await p.click('[data-monad="samael"]');await p.click('#begin');
 // Real shop interaction buys/equips native gear; re-purchasing cannot charge twice.
 await checkpoint(p,{location:1,x:43,y:40,px:30,py:8});await p.click('[data-native="6"]');await p.click('[data-option="22"]');let s=await snapshot(p);assert.equal(s.gold,75);assert.equal(s.weapon,1);assert.equal(s.owned,1);await p.click('[data-option="22"]');assert.equal((await snapshot(p)).gold,75);await p.click('[data-option="23"]');assert.equal((await snapshot(p)).weapon,2);await p.click('[data-option="24"]');s=await snapshot(p);assert.equal(s.gold,25);assert.equal(s.owned,7);assert.equal(s.armor,1);await p.click('#conversation-close');
 // Switching gear spends one enemy turn. Blade damage and robe reduction affect real combat.
 await checkpoint(p,{},'8,7,2,1,0,0,0,0,0,0');await p.locator('#native-equipment summary').click();await p.click('[data-equip="0,1"]');s=await snapshot(p);assert.equal(s.weapon,1);assert.equal(s.turn,1);assert.equal(s.time,0.5);assert.equal(s.hp,47);assert.equal(s.strike,16);await p.click('[data-native="8"]');assert.equal((await snapshot(p)).experience,13);assert.equal((await snapshot(p)).hp,47);
 // Staff reaches two cells and does not shoot through stone.
 await checkpoint(p,{px:1,py:7},'8,2,2,0,0,0,0,0,0,0');await p.click('[data-native="8"]');assert.equal((await p.evaluate(()=>nativeSaveData().dungeon)).split(',')[6],'3');await p.click('[data-native="8"]');assert.equal((await snapshot(p)).experience,13);
 await checkpoint(p,{px:3,py:5},'8,2,2,0,0,0,0,0,0,0');const wall=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.evaluate(()=>nativeAct(8));assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),wall);
 // Level thresholds change damage/capacity; crossing via a kill replenishes Light.
 await checkpoint(p,{experience:24},'1,0,0,0,0,0,0,0,0,0','1,0,0,1,3,7,1,7,5,18,9,3,20');await p.click('[data-native="8"]');s=await snapshot(p);assert.equal(s.level,2);assert.equal(s.light,10);assert.equal(s.maxLight,10);assert.equal(s.strike,14);assert((await p.locator('#native-message').textContent()).includes('level 2'));
 for(const[xp,level]of [[25,2],[59,2],[60,3],[99,3],[100,4]]){await checkpoint(p,{experience:xp},`${6+2*level},0,0,0,0,0,0,0,0,0`);assert.equal((await snapshot(p)).level,level);}
 console.log('PASS outfitter, gear effects, reach, walls and native level thresholds');await p.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
