/* Native scene appearance and wall occlusion, checked in real browser screenshots. */
const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path'),fs=require('node:fs'),crypto=require('node:crypto');
const source=fs.readFileSync(path.resolve(__dirname,'../native/assets/interior-atlas.png'));
assert(fs.readFileSync(path.resolve(__dirname,'../native/interior-pixels.h'),'utf8').includes(crypto.createHash('sha256').update(source).digest('hex')),'Recompile interior artwork');
async function pixels(p){await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const bytes=await p.locator('canvas').screenshot();return p.evaluate(async base64=>{const im=new Image();im.src='data:image/png;base64,'+base64;await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);const data=ctx.getImageData(0,0,c.width,c.height*160/192).data;let violet=0,turquoise=0,gold=0,nonblack=0;for(let i=0;i<data.length;i+=4){const r=data[i],g=data[i+1],b=data[i+2];if(r>65&&g<65&&b>90)violet++;if(r<60&&g>90&&b>100)turquoise++;if(r>170&&g>95&&g<220&&b<120)gold++;if(r+g+b>35)nonblack++;}return{violet,turquoise,gold,nonblack};},bytes.toString('base64'));}
async function dungeon(p,{px=1,py=7,facing=1,enemies='3,7,16,7,5,18,9,3,20',cache=0,scene=2}={}){await p.evaluate(({px,py,facing,enemies,cache,scene})=>{const d=nativeSaveData();Object.assign(d.state,{location:scene,x:scene===4?54:51,y:scene===4?33:47,px,py,quest:3,clue:1,blessing:1,resolution:1,hp:100,food:100});d.growth='8,0,0,0,0,0,0,0,0,0';d.dungeon=`1,${cache},0,${facing},${enemies}`;nativeRestore(JSON.stringify(d));},{px,py,facing,enemies,cache,scene});}
(async()=>{const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});try{
 for(const viewport of [{width:1280,height:720},{width:390,height:844},{width:844,height:390}]){
  const p=await browser.newPage({viewport,hasTouch:viewport.width<1000,deviceScaleFactor:viewport.width<1000?3:1}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.waitForSelector('#welcome[open]');await p.click('#choose-direct');await p.click('[data-monad="ariel"]');await p.click('#begin');
  await p.evaluate(()=>{const d=nativeSaveData();Object.assign(d.state,{x:43,y:40});nativeRestore(JSON.stringify(d));nativeAct(6);});assert.equal(await p.evaluate(()=>nativeSnapshot().location),1);const haven=await p.locator('canvas').screenshot();await p.screenshot({path:'/tmp/quest-interior-haven-'+viewport.width+'.png'});
  // Warm Haven and cool Vesper have different backdrops at identical town coordinates.
  await p.evaluate(()=>{const d=nativeSaveData();Object.assign(d.state,{location:3,x:54,y:40,quest:3,clue:1,blessing:1,resolution:1});d.dungeon='1,0,1,0,3,7,0,7,5,0,9,3,0';nativeRestore(JSON.stringify(d));});assert.equal(await p.evaluate(()=>nativeSnapshot().location),3);await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));assert(!haven.equals(await p.locator('canvas').screenshot()));await p.screenshot({path:'/tmp/quest-interior-vesper-'+viewport.width+'.png'});
  await dungeon(p);assert((await pixels(p)).violet>20,'Horror must be visible down the corridor');await p.screenshot({path:'/tmp/quest-interior-horror-'+viewport.width+'.png'});
  await dungeon(p,{px:1,py:5,enemies:'7,5,16,9,3,18,3,7,20'});assert.equal((await pixels(p)).violet,0,'Walls must hide horrors, not just shade them');assert((await pixels(p)).nonblack>1000,'Masonry must replace the empty wireframe background');
  await dungeon(p,{px:3,py:3,facing:0,enemies:'3,7,0,7,5,0,9,3,0'});assert((await pixels(p)).turquoise>2,'Cache clasp must be visible');await p.screenshot({path:'/tmp/quest-interior-cache-'+viewport.width+'.png'});await p.evaluate(()=>nativeAct(6));assert.equal((await pixels(p)).turquoise,0,'Collected cache disappears');
  await dungeon(p,{px:9,py:1,facing:0,enemies:'3,7,0,7,5,0,9,3,0'});assert((await pixels(p)).gold>10,'Bound memory must render in its chamber');await p.screenshot({path:'/tmp/quest-interior-listener-'+viewport.width+'.png'});
  await p.click('#native-save');const save=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),save);assert((await pixels(p)).gold>10);
  await dungeon(p,{px:1,py:9,facing:0});assert((await pixels(p)).gold>10,'Exit steps must remain visible');await p.evaluate(()=>nativeAct(6));assert.equal(await p.evaluate(()=>nativeSnapshot().location),0);
  assert.deepEqual(errors,[]);await p.close();console.log('PASS interior palettes, dungeon objects, wall occlusion, cache removal and save',viewport);
 }
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
