const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const snap=p=>p.evaluate(()=>JSON.stringify(nativeSaveData()));
async function view(p){await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));return p.evaluate(()=>JSON.parse(nativeCall('quest_view_state','string',[],[])));}
async function tap(p,selector){await p.locator(selector).scrollIntoViewIfNeeded();const b=await p.locator(selector).boundingBox();await p.touchscreen.tap(b.x+b.width/2,b.y+b.height/2);}
async function place(p,location,px,py){await p.evaluate(({location,px,py})=>{const d=nativeSaveData();Object.assign(d.state,{x:location===2?51:43,y:location===2?47:40,location,px,py,quest:3,clue:1,blessing:1,resolution:1,hp:100,food:100});if(location===2)d.dungeon='1,0,0,0,3,7,16,7,5,18,9,3,20';nativeRestore(JSON.stringify(d));},{location,px,py});}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});try{
 for(const viewport of [{width:390,height:844},{width:844,height:390},{width:1280,height:720}]){
  const p=await b.newPage({viewport,hasTouch:true,deviceScaleFactor:viewport.width<1000?3:1}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.waitForSelector('#welcome[open]');await p.click('#choose-direct');await p.click('#begin');
  assert.equal((await view(p)).zoom,1);assert(await p.locator('#native-zoom-out').isDisabled());const unchanged=await snap(p),canvas=await p.locator('canvas').boundingBox();
  for(const zoom of [1.5,2,3]){await tap(p,'#native-zoom-in');const v=await view(p);assert.equal(v.zoom,zoom);assert.equal(v.appliedZoom,zoom);assert(Math.abs(v.width-280/zoom)<.02);assert(Math.abs(v.height-192/zoom)<.02);assert.equal(await snap(p),unchanged);assert.deepEqual(await p.locator('canvas').boundingBox(),canvas);}
  assert(await p.locator('#native-zoom-in').isDisabled());assert.equal(await p.evaluate(()=>nativeCall('quest_set_zoom','number',['number'],[0])),1);assert.equal(await p.evaluate(()=>nativeCall('quest_set_zoom','number',['number'],[50])),3);await p.evaluate(()=>nativeSetZoom(3));
  await p.screenshot({path:'/tmp/quest-qol-zoom-'+viewport.width+'.png'});
  // Preference persists independently of the journey; camera remains centered after real movement.
  await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');assert.equal((await view(p)).zoom,3);assert.equal(await snap(p),unchanged);const old=await view(p);await p.evaluate(()=>nativeAct(4));const moved=await view(p);assert.equal(moved.x-old.x,14);assert.equal(moved.y,old.y);
  // A zoomed town follows the pilgrim and clamps to the original town rectangle at every edge.
  for(const [px,py]of [[20,20],[20,7],[1,1],[38,20]]){await place(p,1,px,py);const v=await view(p);assert(v.x>=0&&v.y>=0&&v.x+v.width<=280.02&&v.y+v.height<=192.02);assert(px*7+3.5>=v.x&&px*7+3.5<=v.x+v.width);assert(py*7+3.5>=v.y&&py*7+3.5<=v.y+v.height);}
  await p.screenshot({path:'/tmp/quest-qol-town-'+viewport.width+'.png'});await place(p,2,1,9);const dungeon=await view(p);assert.equal(dungeon.zoom,3);assert.equal(dungeon.appliedZoom,1);assert.equal(dungeon.width,280);assert.equal(dungeon.height,192);assert.equal(await p.locator('#native-zoom-level').textContent(),'Full view');assert(await p.locator('#native-zoom-in').isDisabled());await place(p,0,0,0);assert.equal((await view(p)).appliedZoom,3);
  // Real trusted touch: act once on DOWN; holding and dragging cannot scroll, repeat, or click a second button.
  await p.locator('[data-native="5"]').scrollIntoViewIfNeeded();const button=await p.locator('[data-native="5"]').boundingBox(),point={x:button.x+button.width/2,y:button.y+button.height/2},cdp=await p.context().newCDPSession(p);const before=await p.evaluate(()=>({turn:nativeSnapshot().turn,y:scrollY}));
  await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{...point,id:1}]});assert.equal(await p.evaluate(()=>nativeSnapshot().turn),before.turn+1);await p.waitForTimeout(1150);assert.equal(await p.evaluate(()=>nativeSnapshot().turn),before.turn+1);
  await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:point.x,y:Math.max(10,point.y-100),id:1}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await p.evaluate(()=>nativeSnapshot().turn),before.turn+1);assert.equal(await p.evaluate(()=>scrollY),before.y);
  await tap(p,'[data-native="5"]');assert.equal(await p.evaluate(()=>nativeSnapshot().turn),before.turn+2);await p.locator('[data-native="5"]').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>nativeSnapshot().turn),before.turn+3);await p.click('[data-native="5"]');assert.equal(await p.evaluate(()=>nativeSnapshot().turn),before.turn+4);
  const protectedState=await p.evaluate(()=>{const b=document.querySelector('[data-native="5"]'),s=getComputedStyle(b);return {selection:s.userSelect,touch:s.touchAction,context:b.dispatchEvent(new Event('contextmenu',{bubbles:true,cancelable:true})),drag:b.dispatchEvent(new Event('dragstart',{bubbles:true,cancelable:true})),select:b.dispatchEvent(new Event('selectstart',{bubbles:true,cancelable:true})),text:getSelection().toString()};});assert.equal(protectedState.selection,'none');assert.equal(protectedState.touch,'none');assert.equal(protectedState.context,false);assert.equal(protectedState.drag,false);assert.equal(protectedState.select,false);assert.equal(protectedState.text,'');
  await p.locator('#native-zoom-reset').click();assert.equal((await view(p)).zoom,1);assert(await p.locator('#native-zoom-out').isDisabled());assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);await p.close();console.log('PASS touch protections, single presses, bounded native zoom, town following, dungeon view, preference and unchanged game state',viewport);
 }
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
