const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});try{
 for(const viewport of [{width:1280,height:720},{width:844,height:390},{width:390,height:844}]){
  const p=await b.newPage({viewport,hasTouch:viewport.width<1000}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.waitForSelector('#welcome[open]');await p.click('#choose-direct');await p.click('[data-monad="samael"]');await p.fill('#character-name','Unbroken Journey');await p.click('#begin');
  for(const location of [0,1,2]){
   await p.evaluate(location=>{const d=nativeSaveData();Object.assign(d.state,{location,x:location===2?51:43,y:location===2?47:40,px:location===1?20:1,py:location===1?20:9,food:0,hp:location===2?0:100,gold:location===0?0:location===1?5:50,quest:3,clue:1,blessing:1,resolution:2,supplies:1,tonics:3});d.dungeon='1,1,2,0,3,7,0,7,5,18,9,3,20';nativeRestore(JSON.stringify(d));nativeSave();},location);
   assert(await p.locator('#native-rescue').isVisible());assert((await p.locator('#native-food').textContent()).includes('0.0'));const saved=await p.evaluate(()=>JSON.stringify(nativeSaveData()));await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');assert.equal(await p.evaluate(()=>JSON.stringify(nativeSaveData())),saved);
   const before=JSON.parse(saved);if(viewport.width>=650){const box=await p.locator('canvas').boundingBox();assert(box.y+box.height<=viewport.height);}await p.screenshot({path:'/tmp/quest-rescue-'+viewport.width+'-'+location+'.png'});await p.click('#native-rescue');const after=await p.evaluate(()=>nativeSaveData());assert.equal(after.state.location,0);assert.equal(after.state.x,43);assert.equal(after.state.y,40);assert.equal(after.state.food,20);assert.equal(after.state.hp,location===2?50:100);assert.equal(after.state.gold,Math.max(0,before.state.gold-10));assert.deepEqual(after.character,before.character);assert.equal(after.dungeon,before.dungeon);for(const k of ['quest','clue','blessing','resolution','supplies','tonics','experience','turn','time'])assert.equal(after.state[k],before.state[k]);assert.equal(await p.locator('#native-rescue').isVisible(),false);await p.click('[data-native="4"]');assert.equal(await p.evaluate(()=>nativeSnapshot().x),44);
  }
  await p.evaluate(()=>{const d=nativeSaveData();d.state.food=10;nativeRestore(JSON.stringify(d));});assert(await p.locator('#native-warning').isVisible());assert((await p.locator('#native-warning').textContent()).includes('Iona'));await p.evaluate(()=>{const d=nativeSaveData();d.state.food=11;nativeRestore(JSON.stringify(d));});assert.equal(await p.locator('#native-warning').isVisible(),false);
  // Previous native save format remains recoverable, even when already stranded.
  await p.evaluate(()=>{const d=nativeSaveData();d.version=2;delete d.dungeon;d.state.food=0;nativeRestore(JSON.stringify(d));});await p.click('[data-native="6"]');assert.equal(await p.evaluate(()=>nativeSnapshot().food),20);assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));assert.deepEqual(errors,[]);console.log('PASS coast/town/dungeon rescue, progress, old save, warning',viewport);await p.close();
 }
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
