const {chromium}=require('playwright'),assert=require('node:assert/strict'),path=require('node:path');
const first='1,1,1,0,3,7,0,7,5,0,9,3,0';
const defaultTrail='1,0,0,0,0,0,0,0,36,52,52,52,32,55,24,45,53,32,55,59,40';
const snap=p=>p.evaluate(()=>nativeSnapshot()),trail=p=>p.evaluate(()=>JSON.parse(nativeCall('quest_trail_state','string',[],[]))),saved=p=>p.evaluate(()=>JSON.stringify(nativeSaveData()));
async function begin(p,monad){await p.goto('file://'+path.resolve(__dirname,'../index.html'));await p.waitForSelector('#welcome[open]');await p.click('#choose-direct');await p.click('[data-monad="'+monad+'"]');await p.click('#begin');}
async function fixture(p,{state={},active=0,growth='16,0,0,0,0,0,0,0,0,0',ending=0}={}){await p.evaluate(({first,defaultTrail,state,active,growth,ending})=>{
 const d=nativeSaveData();Object.assign(d.state,{location:0,x:31,y:55,px:0,py:0,hp:50,food:100,gold:50,experience:200,quest:3,clue:1,blessing:1,resolution:1,turn:0,time:0,tonics:1},state);d.dungeon=first;d.growth=growth;const t=defaultTrail.split(',');t[3]=active;d.trail=t.join(',');d.chapter=nativeCall('quest_chapter_default','string',[],[]);
 if(ending){const c=d.chapter.split(',');c[1]=4;c[2]=3;c[3]=1;c[4]=1;c[6]=ending;d.chapter=c.join(',');}nativeRestore(JSON.stringify(d));
 },{first,defaultTrail,state,active,growth,ending});}
async function place(p,x,y,extra={},growth){await p.evaluate(({x,y,extra,growth})=>{const d=nativeSaveData();Object.assign(d.state,{x,y},extra);if(growth)d.growth=growth;nativeRestore(JSON.stringify(d));},{x,y,extra,growth});}
async function select(p,choice){await p.click('[data-native="6"]');await p.click('[data-option="'+choice+'"]');await p.click('#conversation-close');}
async function visibleColor(p,color){await p.evaluate(()=>new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve))));const png=await p.locator('canvas').screenshot();return p.evaluate(async({base64,color})=>{const image=new Image();image.src='data:image/png;base64,'+base64;await image.decode();const c=document.createElement('canvas');c.width=image.width;c.height=image.height;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);const pixels=ctx.getImageData(0,0,c.width,c.height).data;let found=0;for(let i=0;i<pixels.length;i+=4)if(color.every((value,k)=>pixels[i+k]>=value[0]&&pixels[i+k]<=value[1]))found++;return found;},{base64:png.toString('base64'),color});}
(async()=>{const b=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,headless:true});try{
 for(const [monad,width,height]of [['ariel',1280,720],['samael',844,390],['raphael',390,844],['jophiel',1280,720],['lilith',390,844]]){
  const p=await b.newPage({viewport:{width,height},hasTouch:width<1000}),errors=[];p.on('pageerror',e=>errors.push(e.message));await begin(p,monad);await fixture(p);
  // Bumping the real world marker starts a duel without paying a movement turn.
  await p.evaluate(()=>nativeAct(4));assert.equal((await trail(p)).active,1);assert.equal((await snap(p)).x,31);assert.equal((await snap(p)).turn,0);assert.equal((await snap(p)).food,100);
  await p.click('#native-power');let s=await snap(p),t=await trail(p);assert.equal(s.light,13);assert.equal(s.turn,1);assert.equal(s.time,1);assert.equal(s.food,99.9);
  if(monad==='ariel'){assert.equal(s.hp,52);assert.equal(s.ward,2);}if(monad==='samael'){assert.equal(t.active,0);assert.equal(t.foes[0][2],0);assert.equal(s.experience,218);assert.equal(s.gold,62);}if(monad==='raphael'){assert.equal(s.hp,87);assert.equal(s.ward,0);}if(monad==='jophiel'){assert.equal(s.hp,50);assert.equal(s.focus,9);assert.equal((await p.evaluate(()=>nativeSaveData().growth)).split(',')[7],'2');}if(monad==='lilith'){assert.equal(s.hp,50);assert.equal(s.veil,2);assert.equal(s.focus,13);}
  if(t.active)assert(await visibleColor(p,[[70,255],[0,65],[90,255]])>5,'Native horror marker must render');await p.screenshot({path:'/tmp/quest-trail-'+monad+'.png'});const effect=await saved(p);await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');assert.equal(await saved(p),effect);
  if(t.active){await p.evaluate(()=>nativeAct(1));assert.equal(await saved(p),effect);const hp=(await snap(p)).hp;await p.click('[data-native="14"]');assert.equal((await trail(p)).active,0);assert.equal((await trail(p)).cooldown,3);assert.equal((await snap(p)).hp,hp);assert.equal((await snap(p)).ward,0);assert.equal((await snap(p)).veil,0);assert.equal((await snap(p)).focus,0);assert.equal((await snap(p)).time,1.5);await p.evaluate(()=>{nativeAct(3);nativeAct(3);nativeAct(3);});assert.equal((await trail(p)).cooldown,0);assert.equal((await trail(p)).active,0);}
  assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));if(width>=650){assert.equal(await p.evaluate(()=>scrollY),0);const box=await p.locator('canvas').boundingBox();assert(box.y+box.height<=height);}assert.deepEqual(errors,[]);console.log('PASS trail contact, gift, saved effects, escape and layout',monad);await p.close();
 }
 const p=await b.newPage();await begin(p,'jophiel');await fixture(p,{state:{x:33,y:54}});await p.evaluate(()=>nativeAct(3));assert.equal((await trail(p)).active,1);assert.equal((await snap(p)).time,1);assert.equal((await snap(p)).food,99.5);assert.equal((await snap(p)).hp,50);
 await fixture(p,{active:3,state:{x:54,y:59,hp:100},growth:'16,7,1,1,0,0,0,0,0,0'});
 // Real gear damage and armor; wounded monsters stay wounded after escape.
 await p.click('[data-native="8"]');assert.equal((await trail(p)).enemyHP,18);assert.equal((await snap(p)).hp,92);await p.click('[data-native="14"]');assert.equal((await trail(p)).foes[2][2],18);
 // Idle has no combat turn; switching gear and a tonic each give exactly one response.
 await fixture(p,{active:1,growth:'16,7,1,1,0,0,0,0,0,0'});const idle=await saved(p);await p.waitForTimeout(150);assert.equal(await saved(p),idle);await p.locator('#native-equipment summary').click();await p.click('[data-equip="0,2"]');assert.equal((await snap(p)).turn,1);assert.equal((await snap(p)).hp,46);await p.click('[data-native="7"]');assert.equal((await snap(p)).turn,2);assert.equal((await snap(p)).hp,67);assert.equal((await snap(p)).tonics,0);
 // Death and exhausted food can be saved, resumed and rescued with both quests intact.
 await fixture(p,{active:3,state:{x:54,y:59,hp:1}});await p.click('[data-native="8"]');assert.equal((await snap(p)).hp,0);const wounded=(await trail(p)).enemyHP;const dead=await saved(p);await p.evaluate(()=>nativeAct(8));assert.equal(await saved(p),dead);await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');await p.click('#native-rescue');assert.equal((await trail(p)).active,0);assert.equal((await trail(p)).foes[2][2],wounded);assert.equal((await snap(p)).x,43);assert.equal((await snap(p)).hp,50);assert.equal(await p.evaluate(()=>nativeSaveData().dungeon),first);
 await fixture(p,{active:1,state:{food:0.05}});await p.click('[data-native="8"]');assert.equal((await snap(p)).food,0);const exhausted=await saved(p);await p.evaluate(s=>nativeRestore(s),exhausted);await p.click('#native-rescue');assert.equal((await snap(p)).food,20);
 // The same 3 road steps move markers repeatably and can never spill into quest roads.
 await fixture(p,{state:{x:43,y:40}});await p.evaluate(()=>{nativeAct(4);nativeAct(4);nativeAct(4);});const roaming=await trail(p);assert.notDeepEqual(roaming.travelers,[[36,52],[52,52]]);assert.notDeepEqual(roaming.foes.map(f=>f.slice(0,2)),[[32,55],[45,53],[55,59]]);await fixture(p,{state:{x:43,y:40}});await p.evaluate(()=>{nativeAct(4);nativeAct(4);nativeAct(4);});assert.deepEqual(await trail(p),roaming);
 // Saved-marker bounds, impossible duels, overlaps, overflow and effects reject atomically.
 const good=await saved(p);for(const mutate of [t=>t[3]=4,t=>t[12]=58,t=>{t[3]=1;t[14]=0;},t=>{t[15]=t[12];t[16]=t[13];},t=>t[0]='9999999999999999999999999999999999999']){const current=JSON.parse(good),values=current.trail.split(',');mutate(values);current.trail=values.join(',');assert(await p.evaluate(s=>{try{nativeRestore(s);return false;}catch{return true;}},JSON.stringify(current)));assert.equal(await saved(p),good);}
 const bad=JSON.parse(good);bad.growth='16,0,0,0,3,0,0,0,0,0';assert(await p.evaluate(s=>{try{nativeRestore(s);return false;}catch{return true;}},JSON.stringify(bad)));assert.equal(await saved(p),good);
 // Existing version-five saves preserve both chapters and relocate a new spawn off the player.
 for(const [x,y]of [[32,55],[45,53],[55,59]]){await fixture(p,{state:{x:43,y:40},ending:2,growth:'5,7,2,1,0,0,0,0,0,0'});await p.evaluate(({x,y})=>{const d=nativeSaveData();d.version=5;delete d.trail;d.state.x=x;d.state.y=y;nativeRestore(JSON.stringify(d));},{x,y});assert.equal((await snap(p)).x,x);assert.equal((await snap(p)).y,y);assert.equal((await snap(p)).choir,2);assert.equal((await snap(p)).vesperStage,4);assert.equal((await snap(p)).light,5);assert.equal((await snap(p)).weapon,2);assert(!(await trail(p)).foes.some(f=>f[0]===x&&f[1]===y&&f[2]>0));}
 console.log('PASS world gear, tonic, death/exhaustion, roaming, atomic imports and version-five migration');
 // Actual native conversations reflect the Monad and both earlier quest outcomes.
 await fixture(p,{state:{x:36,y:53,food:80},ending:1});assert(await visibleColor(p,[[170,255],[85,190],[0,65]])>5,'Native traveler marker must render');await p.click('[data-native="6"]');assert((await p.locator('#conversation-text').textContent()).includes('Jophiel'));assert((await p.locator('#conversation-text').textContent()).includes("Listener's freedom"));const locked=await saved(p);await p.keyboard.press('ArrowUp');assert.equal(await saved(p),locked);await p.click('[data-option="80"]');assert.equal((await snap(p)).food,70);assert.equal((await snap(p)).experience,212);assert.equal((await snap(p)).tonics,2);await p.evaluate(()=>nativeCall('quest_option','number',['number'],[80]));assert.equal((await snap(p)).experience,212);await p.click('#conversation-close');
 await place(p,52,53);await p.click('[data-native="6"]');assert((await p.locator('#conversation-text').textContent()).includes("Vesper's names have returned"));await p.click('[data-option="84"]');await p.click('#conversation-close');assert.equal((await snap(p)).gold,58);
 await place(p,41,29,{hp:50},'3,0,0,0,0,0,0,0,0,0');assert(await visibleColor(p,[[0,100],[150,255],[165,255]])>5,'Native discovery marker must render');await select(p,83);assert.equal((await snap(p)).hp,65);assert.equal((await snap(p)).light,18);const springXP=(await snap(p)).experience;await place(p,41,29,{hp:50},'3,0,0,0,0,0,0,0,0,0');await select(p,83);assert.equal((await snap(p)).experience,springXP);assert.equal((await snap(p)).hp,50);
 await place(p,49,56);await select(p,86);assert.equal((await snap(p)).owned,2);assert.equal((await snap(p)).weapon,0);assert.equal((await snap(p)).gold,73);const journal=await saved(p);await p.reload();await p.waitForSelector('#welcome[open]');await p.click('#welcome-resume');assert.equal(await saved(p),journal);assert.equal((await trail(p)).sites.filter(Boolean).length,4);assert.equal(await p.locator('#native-journal li').count(),4);
 // Alternate discovery choices have distinct costs/rewards and cannot exhaust food.
 await fixture(p,{state:{x:36,y:53,food:10},ending:2});await p.click('[data-native="6"]');await p.click('[data-option="80"]');assert.equal((await snap(p)).food,10);assert.equal((await trail(p)).sites[0],0);await p.click('[data-option="81"]');await p.click('#conversation-close');assert.equal((await snap(p)).experience,208);
 await place(p,52,53);await p.click('[data-native="6"]');assert((await p.locator('#conversation-text').textContent()).includes('Vesper shelters'));await p.click('[data-option="85"]');await p.click('#conversation-close');assert.equal((await snap(p)).tonics,2);
 await place(p,49,56,{gold:4});await p.click('[data-native="6"]');await p.click('[data-option="87"]');assert.equal((await trail(p)).sites[3],0);await p.click('#conversation-close');await place(p,49,56,{gold:50},'3,0,0,0,0,0,0,0,0,0');await select(p,87);assert.equal((await snap(p)).gold,45);assert.equal((await trail(p)).sites[3],2);assert.equal((await snap(p)).light,18);assert.equal((await snap(p)).owned,0);
 console.log('PASS discoveries, Monad/quest-specific lore, all reward branches, journal and one-time rewards');await p.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exit(1)});
