"""Compile the production PNG into native RGBA data; no browser asset requests.

Requires Pillow only when changing artwork. The generated header is committed,
so normal native/CI builds do not need a Python imaging dependency.
"""
from pathlib import Path
import hashlib
from PIL import Image
root = Path(__file__).resolve().parents[1]
for name, symbol, header in [('lantern-atlas', 'art_pixels', 'art-pixels.h'), ('interior-atlas', 'interior_pixels', 'interior-pixels.h')]:
    source = root / f'native/assets/{name}.png'
    image = Image.open(source).convert('RGBA')
    if image.size != (112, 128):
        raise ValueError('Expected a 4 by 4 atlas of 28 by 32 pixel tiles')
    pixels = list(image.get_flattened_data())
    for i, (_, _, _, alpha) in enumerate(pixels):
        if alpha not in (0, 255) or i // 112 < 64 and alpha != 255:
            raise ValueError('Terrain must be opaque and sprites use binary alpha')
    values = [(r << 24 | g << 16 | b << 8 | a) if a else 0 for r, g, b, a in pixels]
    lines = [', '.join(f'0x{v:08x}u' for v in values[i:i + 16]) for i in range(0, len(values), 16)]
    (root / f'native/{header}').write_text(f'/* Generated by tools/compile-art.py from {name}.png. SHA256: ' + hashlib.sha256(source.read_bytes()).hexdigest() + f' */\nstatic const unsigned int {symbol}[112*128] = {{\n' + ',\n'.join(lines) + '\n};\n')
    print('Compiled 16 original art tiles:', name)
